Added Container Registry storage
redhat-appstudio/jvm-build-service pull request #128
Opened 2022-07-25 01:00 UTC by phillip-kruger

This PR change the Deployer in hacbs-sidecar to load the deployer from a factory and then have the ability to add more deployer.
The current default is still S3 for now, but this PR also adds a Container Registry Storage option.

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

2022-07-25 01:51 UTC, stuartwdouglas commented
/approve

2022-07-25 02:36 UTC, stuartwdouglas requested changes
Looks good, just a few minor things. I will hold of on merging it though until we have stability in the e2e tests.

2022-07-25 02:36 UTC, stuartwdouglas commented on java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/Gav.java
> +    private String groupId;
I know it does not really matter here but these should really be immutable. In general mutability + equals/hashCode can result in lots of problems, as the hash code would change if you modify the object.

2022-07-25 02:36 UTC, stuartwdouglas commented on java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/ImageData.java
> +    private Set<Gav> gavs;
Same here.

2022-07-25 18:38 UTC, gabemontero commented
/ok-to-test

2022-07-26 00:37 UTC, gabemontero commented
with https://github.com/redhat-appstudio/jvm-build-service/pull/129 in repo e2e's are green

/retest

2022-07-26 00:38 UTC, gabemontero commented
though the compile is failing now at least in https://github.com/redhat-appstudio/jvm-build-service/runs/7493797597?check_suite_focus=true

2022-07-26 05:38 UTC, phillip-kruger commented
@stuartwdouglas seems like the error has something to do with testcontainers that needs ryuk to performs fail-safe cleanup of containers. see https://www.testcontainers.org/features/configuration/

How does other builds that needs testcontainers handle this ?

2022-07-26 22:58 UTC, stuartwdouglas commented
What makes you say that? It looked like docker.io failed to service an image to me.

2022-07-26 22:58 UTC, stuartwdouglas commented
/retest

2022-07-28 00:44 UTC, stuartwdouglas approved these changes

2022-07-29 08:38 UTC, stuartwdouglas commented
/retest

2022-07-29 19:41 UTC, gabemontero commented
/retest

2022-07-31 23:16 UTC, stuartwdouglas commented
/retest

2022-08-01 00:23 UTC, phillip-kruger commented
/retest

2022-08-01 05:41 UTC, stuartwdouglas commented
/retest

2022-08-01 09:23 UTC, merged