PLNSRVCE-528 fix issue with contaminated builds
redhat-appstudio/jvm-build-service pull request #132
Opened 2022-07-26 08:38 UTC by stuartwdouglas

2022-07-26 14:36 UTC, gabemontero commented
Is there something present on a artifactbuild or dependencybuild CRD instance as a result of this fix that we could cross-verify against in the in-repo e2e (assuming the repo we settle on for our in-repo tests has a contaminant) ?

 I *think* https://github.com/stuartwdouglas/code-with-quarkus has a contaminant if we let it run long enough. But whether we can tolerate https://github.com/stuartwdouglas/code-with-quarkus in our PR e2e's long term because of resource constraints is TBD (I believe I've seen intermittent instances of resources constraints during maven download in a case or two.

When I start trying out https://github.com/stuartwdouglas/shaded-java-app today I'll see if it has one (though you quite possibly know that off the top of your head @stuartwdouglas )

/retest

for pipeline as code failures

2022-07-26 16:18 UTC, gabemontero commented
> Is there something present on a artifactbuild or dependencybuild CRD instance as a result of this fix that we could cross-verify against in the in-repo e2e (assuming the repo we settle on for our in-repo tests has a contaminant) ?
> 
> I _think_ https://github.com/stuartwdouglas/code-with-quarkus has a contaminant if we let it run long enough. But whether we can tolerate https://github.com/stuartwdouglas/code-with-quarkus in our PR e2e's long term because of resource constraints is TBD (I believe I've seen intermittent instances of resources constraints during maven download in a case or two.)
> 
> When I start trying out https://github.com/stuartwdouglas/shaded-java-app today I'll see if it has one (though you quite possibly know that off the top of your head @stuartwdouglas )
> 
> /retest
> 
> for pipeline as code failures

yeah no contaminated builds with https://github.com/stuartwdouglas/shaded-java-app 
which I think we want to switch to because I am still seeing intermittent resource constraints with the quarkus repo

2022-07-26 16:58 UTC, gabemontero commented
> > Is there something present on a artifactbuild or dependencybuild CRD instance as a result of this fix that we could cross-verify against in the in-repo e2e (assuming the repo we settle on for our in-repo tests has a contaminant) ?
> > I _think_ https://github.com/stuartwdouglas/code-with-quarkus has a contaminant if we let it run long enough. But whether we can tolerate https://github.com/stuartwdouglas/code-with-quarkus in our PR e2e's long term because of resource constraints is TBD (I believe I've seen intermittent instances of resources constraints during maven download in a case or two.)
> > When I start trying out https://github.com/stuartwdouglas/shaded-java-app today I'll see if it has one (though you quite possibly know that off the top of your head @stuartwdouglas )
> > /retest
> > for pipeline as code failures
> 
> yeah no contaminated builds with https://github.com/stuartwdouglas/shaded-java-app which I think we want to switch to because I am still seeing intermittent resource constraints with the quarkus repo

Correction - one contaminated 

`dependencybuild.jvmbuildservice.io/d1f3a6d34e891ddc731c33f45f8e05de   https://github.com/netty/netty.git              netty-4.1.74.Final                   DependencyBuildStateContaminated   
`

Though looking at its yaml, I don't see how we could cross ref with the changes here.

/approve
/lgtm

2022-07-26 22:18 UTC, stuartwdouglas commented
@gabemontero we should verify that the jctools ABR gets created, and then that Netty rebuilds.

If you want to test the end state I think we really need to verify that Netty is complete, JCTools is complete, and Netty started after the JCTools build.

2022-07-26 22:38 UTC, stuartwdouglas commented
@gabemontero I have had an attempted at adding an E2E test for this flow.

2022-07-26 23:02 UTC, gabemontero requested changes
just a couple of minor suggestions @stuartwdouglas 

I've seen enough odd errors from the api server over the years ... reporting them in this case always proves helpful in those rare / intermittent cases

2022-07-26 23:02 UTC, gabemontero commented on openshift-with-appstudio-test/e2e/jvm_build_service_test.go
> +			dbList, err := jvmClient.JvmbuildserviceV1alpha1().DependencyBuilds(ta.ns).List(context.TODO(), metav1.ListOptions{})
log this error if it is not nil ... might help us in resource constraint situations

2022-07-26 23:09 UTC, stuartwdouglas commented
Done

2022-07-26 23:11 UTC, gabemontero approved these changes
cool let's see how it does

2022-07-26 23:17 UTC, stuartwdouglas commented
The failure is unrelated but I have pushed a fix to this branch

2022-07-27 04:03 UTC, stuartwdouglas commented
/retest

2022-07-27 04:04 UTC, stuartwdouglas commented
Somewhat worryingly it looks like the sidecar has just randomly stopped accepting connections, then is still attempting to do IO after the build is over. I am really not sure what is happening there.

2022-07-27 12:33 UTC, gabemontero commented
> Somewhat worryingly it looks like the sidecar has just randomly stopped accepting connections, then is still attempting to do IO after the build is over. I am really not sure what is happening there.

Ok @stuartwdouglas coming in this AM and looking here, the e2e is green.

Thas said, unless you already this and feel otherwise, I can bring up an openshift cluster today, check out your PR, and retest locally, and see if I see failures, or see the sidecar anomaly your are describing and try to debug.  I'll post any findings here, and we can reconvene later my Wednesday / your Thursday and decide what we want to do.

2022-07-27 12:56 UTC, stuartwdouglas commented
I don't think it is related in any way, just something I would like to understand, it could be a problem with the sidecar, or something environmental.

2022-07-27 12:56 UTC, merged

2022-07-27 12:58 UTC, gabemontero commented
> I don't think it is related in any way, just something I would like to understand, it could be a problem with the sidecar, or something environmental.

Cool deal.  If I have cycles I might try today with this merged if I can reproduced / identify it, for educational purposes if anything else.

2022-07-27 20:37 UTC, gabemontero commented
> > I don't think it is related in any way, just something I would like to understand, it could be a problem with the sidecar, or something environmental.
> 
> Cool deal. If I have cycles I might try today with this merged if I can reproduced / identify it, for educational purposes if anything else.

So yeah I discovered first hand the debug difficulties sidecars provide ;-)

in the end, no discoveries as to what if anything is up with the sidecar or env, but it did lead to some general test robustness tweaks, as well as *potential* sidecar debug updates I'll note to you in my catch all for today, https://github.com/redhat-appstudio/jvm-build-service/pull/135