Create a dependencyBuild directly
redhat-appstudio/jvm-build-service pull request #1610
Opened 2024-04-24 08:06 UTC by rnc

2024-04-25 15:37 UTC, rnc commented on pkg/reconciler/dependencybuild/dependencybuild.go
> +		if err := controllerutil.SetOwnerReference(&ab, db, r.scheme); err != nil {
After further testing this isn't correct I think. It needs to be `controllerutil.SetOwnerReference(db, &ab, r.scheme)` but I don't think we can have it in this function as the caller calls patchStatus.

2024-04-25 16:47 UTC, rnc commented on pkg/reconciler/dependencybuild/dependencybuild.go
> +		if err := controllerutil.SetOwnerReference(&ab, db, r.scheme); err != nil {
I am trying an experimental change to update it elsewhere but currently hitting a mixture of rbac problems and 'object has been modified' ....

2024-04-26 06:43 UTC, stuartwdouglas requested changes
I think that in addition to the CLI changes we also need a way to rebuild the DependencyBuild objects, at the moment this is handled via annotations on the ArtifactBuild, but if there is not corresponding ArtifactBuild then we can't directly rebuild them.

2024-04-26 06:43 UTC, stuartwdouglas commented on pkg/reconciler/dependencybuild/dependencybuild.go
> +			err = r.createArtifacts(ctx, log, pr, db, deployed)
I don't think we need to create `ArtifactBuild` objects for this case, we already have `RebuiltArtifact` as a marker that the objects were created.

2024-04-26 06:43 UTC, stuartwdouglas commented on java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/artifactwatch/ScmLookup.java
> +                                // from existing dependency.
Like I mentioned below I don't think we need to handle this case.

2024-05-06 03:01 UTC, merged