Update Ant Ivy default resolver
redhat-appstudio/jvm-build-service pull request #506
Opened 2023-02-17 15:18 UTC by dwalluck

2023-02-17 16:36 UTC, dwalluck commented
/test jvm-build-service-in-repo-apicurio-e2e

2023-02-23 04:34 UTC, stuartwdouglas approved these changes

2023-02-23 04:35 UTC, stuartwdouglas requested changes
The failure looks related

2023-02-24 19:06 UTC, dwalluck commented
> The failure looks related

Fixed. The code was OK, but test wasn't updated for the new code.

In the previous code, the default Maven repo had the same name as the chain (which includes the Maven repo and the maven local repo), so it wasn't using the chain.

2023-02-27 00:09 UTC, stuartwdouglas approved these changes

2023-02-27 00:09 UTC, merged