STONEBLD-1518: Allow disabling plugins from YAML
redhat-appstudio/jvm-build-service pull request #923
Opened 2023-11-15 19:45 UTC by dwalluck

2023-11-16 02:31 UTC, stuartwdouglas requested changes

2023-11-16 02:31 UTC, stuartwdouglas commented on java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/maven/MavenPrepareCommand.java
> +        BuildRecipeInfo info = BuildRecipe.BUILD.getHandler().parse(Path.of(PLUGIN_INFO + "/maven.yaml"));
This is the preprocessor command, you need to use the disabledPlugins command line argument that was passed in, maven.yaml is not present here.

2023-11-16 02:31 UTC, stuartwdouglas commented on pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
> +	DisabledPlugins     string               `json:"disabledPlugins,omitempty"`
This should really be a string array. I know at the moment it is just used as a comma separated list but it is still better to preserve the structure.

2023-11-21 23:25 UTC, dwalluck commented on java-components/build-request-processor/pom.xml
> +        <dependency>
Not sure why this change was required. IDEA seemed to want it.

2023-11-21 23:36 UTC, dwalluck commented on java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RecipeManager.java
> +                    results.addAll(BuildRecipe.BUILD.getHandler().parse(path.get()).getDisabledPlugins());
@stuartwdouglas Is this correct? Merging if multiple recipe dirs...

2023-11-29 00:38 UTC, stuartwdouglas commented
/retest

2023-11-29 08:28 UTC, rnc commented
Could we squash to get rid of `Merge remote-tracking branch 'upstream/main' into STONEBLD-1518`  (or use rebase in future?) ?

2023-11-29 19:45 UTC, stuartwdouglas commented
/retest

2023-11-29 21:27 UTC, stuartwdouglas commented
/retest

2023-12-04 06:13 UTC, merged